### ISSUE TITLE
.edit and .say: ability to use these commands without pinging users or roles mentioned in the content

### ISSUE THREAD

**Issue by visceralfield** [TrashMonks/Ereshkigal-Prime#27]
(see also https://github.com/TrashMonks/Ereshkigal/issues/25)

When running the `edit` or `say` commands with a text argument that mentions users or roles, posting the command message will ping those roles (followed by ereshkigal immediately deleting the command message). When ereshkigal herself posts the subsequent message containing that text argument in the case of `say`, it will also ping the mentioned users or roles.

To update the `server-info` channel, we need to post a message that mentions almost every role in the server. It would be best if there were a way to use `say` and `edit` on this message that did not result in pinging thousands of users, for server management reasons.

**Comment by HeladoDeBrownie** [comment]
resolved by f959f93646bba0356f456dcd617696c224d62e82
