### ISSUE TITLE
edit, say, & post: document under what circumstances these commands will ping mentioned users and roles

### ISSUE THREAD

**Issue by visceralfield** [TrashMonks/Ereshkigal-Prime#32]
it would be useful if, when running `.help edit`, `.help say`, and `.help post`, the response from Ereshkigal documented whether or not using the command in question will ping mentioned users or roles (or the conditions under which using the command will or won't ping).

**Comment by visceralfield** [comment]
clarification: it would be useful to not only document whether or not Ereshkigal herself pings users, but whether the actual command message will ping mentioned users as well -- i.e. attaching a file containing mentions will not ping people, but having mentions in the text of the command message will (this is relevant for staff posting and editing in #server-info, where every role in the server is mentioned in posts)

**Comment by HeladoDeBrownie** [comment]
resolved by c81654caa6631abfaeb55335d1421f0a4ce95bd9
