### ISSUE TITLE
Shortcut to person's onboarding questionnaire from created ticket

### ISSUE THREAD

**Issue by librarianmage** [TrashMonks/Ereshkigal-Prime#37]
it would be helpful if there was a link to a person's questionnaire from the ticket, since current methods to switch between the two are rather clunky

**Comment by HeladoDeBrownie** [comment]
helped by 2d2673792277bac69e628aad34675172d414a727; let me know if the new `onboard app` subcommand is close enough or if we need more

**Comment by HeladoDeBrownie** [comment]
we're not there just yet, but a possible solution occurred to me: listen for channel creations or permission edits in onboarding categories. if a user is found to be added explicitly to a channel there, assume the ticket is for them and automatically copy over their whole questionnaire

**Comment by HeladoDeBrownie** [comment]
no longer necessary. we've retired the old onboarding system
